# Day 01 — Basics

- name: Install Nginx on Afzal server
  hosts: all
  become: yes

  tasks:
    - name: Install nginx
      yum:
        name: nginx
        state: present



docker --version
docker run ubuntu echo "Hello Afzal"



FROM ubuntu:22.04
CMD ["echo", "Hello Afzal"]



Done day one

this side afzal

only suggest me 

hey team are you ok