Day 03 — Ansible, Terraform & Kubernetes Basics
🔹 Ansible — Install Apache and Start Service

- name: Install Nginx and Start Apache
  hosts: all
  become: yes
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present

    - name: Start apache
      service:
        name: httpd
        state: started
        enabled: yes



🔹 Terraform — EC2 Instance (t3.medium)

provier "aws" {
  region = "us-east-1"
}

resources "aws-instance" "AfzalEC2" {
  ami           = "ami-oqhdfbnehcb338"
  instance_type = "t3.medium"
  tags = {
    Name = "Afzal-T3"
  }
}

🔹 Kubernetes — Create a ReplicaSet with 3 Replicas

apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: afzal-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: afzal-app
  template:
    metadata:
      labels:
        app: afzal-app
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - conatinerPort: 80


🔹 Shell Script — User Info
#!/bin/bash

echo "Current user: $(whoami)"
echo "Current user groups: $(groups)"


🔹 Docker
# Docker File for Nginx Web Server

FROM nginx:latest
COPY index.html /usr/share/nginx/html/index.html

# HTML

<h1>Hello Afzal</h1>

# Bash
# Real Path
/usr/share/nginx/html

# Bash

docker build -t afzal-nginx
docker run -d -p 80:80 afzal-nginx